FROM node:slim

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install
# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY app.js .

EXPOSE 3001
CMD [ "node", "app.js" ]
